parameters:
    mrtn_json_api.http_client.class:                'Mikemirten\Component\JsonApi\HttpClient\HttpClient'
    mrtn_json_api.http_client.adapter.guzzle.class: 'Mikemirten\Component\JsonApi\HttpClient\Adapter\GuzzleAdapter'
    mrtn_json_api.route_repository.class:           'Mikemirten\Bundle\JsonApiBundle\Routing\RouteRepository'
    mrtn_json_api.resource_client.class:            'Mikemirten\Bundle\JsonApiBundle\HttpClient\ResourceBasedClient'
    mrtn_json_api.http_client.guzzle.class:         'GuzzleHttp\Client'

    mrtn_json_api.http_client.decorator.event_dispatcher.class: 'Mikemirten\Component\JsonApi\HttpClient\Decorator\SymfonyEventDispatcherDecorator'

services:
    mrtn_json_api.http_client:
        class: '%mrtn_json_api.http_client.class%'
        arguments:
            - '@mrtn_json_api.http_client.decorator.event_dispatcher'
            - '@mrtn_json_api.document_hydrator'

    mrtn_json_api.http_client.adapter.guzzle:
        class: '%mrtn_json_api.http_client.adapter.guzzle.class%'
        public: false
        arguments:
            - '@mrtn_json_api.http_client.guzzle'

    mrtn_json_api.http_client.guzzle:
        class: '%mrtn_json_api.http_client.guzzle.class%'
        public: false

    mrtn_json_api.http_client.decorator.event_dispatcher:
        class: '%mrtn_json_api.http_client.decorator.event_dispatcher.class%'
        public: false
        arguments:
            - '@mrtn_json_api.http_client.adapter.guzzle'
            - '@event_dispatcher'