parameters:
    mrtn_json_api.document_hydrator.class: 'Mikemirten\Component\JsonApi\Hydrator\DocumentHydrator'

    mrtn_json_api.document_hydrator.extension.links.class:        'Mikemirten\Component\JsonApi\Hydrator\Extension\LinksExtension'
    mrtn_json_api.document_hydrator.extension.metadata.class:     'Mikemirten\Component\JsonApi\Hydrator\Extension\MetadataExtension'
    mrtn_json_api.document_hydrator.extension.relationship.class: 'Mikemirten\Component\JsonApi\Hydrator\Extension\RelationshipExtension'
    mrtn_json_api.document_hydrator.extension.errors.class:       'Mikemirten\Component\JsonApi\Hydrator\Extension\ErrorsExtension'
    mrtn_json_api.document_hydrator.extension.included.class:     'Mikemirten\Component\JsonApi\Hydrator\Extension\IncludedExtension'
    mrtn_json_api.document_hydrator.extension.jsonapi.class:      'Mikemirten\Component\JsonApi\Hydrator\Extension\JsonApiExtension'

services:
    mrtn_json_api.document_hydrator:
        class: '%mrtn_json_api.document_hydrator.class%'

    mrtn_json_api.document_hydrator.extension.links:
        class: '%mrtn_json_api.document_hydrator.extension.links.class%'
        public: false
        tags:
            - { name: 'mrtn_json_api.document_hydrator.extension' }

    mrtn_json_api.document_hydrator.extension.metadata:
        class: '%mrtn_json_api.document_hydrator.extension.metadata.class%'
        public: false
        tags:
            - { name: 'mrtn_json_api.document_hydrator.extension' }

    mrtn_json_api.document_hydrator.extension.relationship:
        class: '%mrtn_json_api.document_hydrator.extension.relationship.class%'
        public: false
        tags:
            - { name: 'mrtn_json_api.document_hydrator.extension' }

    mrtn_json_api.document_hydrator.extension.errors:
        class: '%mrtn_json_api.document_hydrator.extension.errors.class%'
        public: false
        tags:
            - { name: 'mrtn_json_api.document_hydrator.extension' }

    mrtn_json_api.document_hydrator.extension.included:
        class: '%mrtn_json_api.document_hydrator.extension.included.class%'
        public: false
        tags:
            - { name: 'mrtn_json_api.document_hydrator.extension' }

    mrtn_json_api.document_hydrator.extension.jsonapi:
        class: '%mrtn_json_api.document_hydrator.extension.jsonapi.class%'
        public: false
        tags:
            - { name: 'mrtn_json_api.document_hydrator.extension' }