parameters:
    mrtn_json_api.document_hydrator.class: 'Mikemirten\Component\JsonApi\Hydrator\DocumentHydrator'

    mrtn_json_api.document_hydrator.extension.links.class:        'Mikemirten\Component\JsonApi\Hydrator\Extension\LinksExtension'
    mrtn_json_api.document_hydrator.extension.metadata.class:     'Mikemirten\Component\JsonApi\Hydrator\Extension\MetadataExtension'
    mrtn_json_api.document_hydrator.extension.relationship.class: 'Mikemirten\Component\JsonApi\Hydrator\Extension\RelationshipExtension'
    mrtn_json_api.document_hydrator.extension.errors.class:       'Mikemirten\Component\JsonApi\Hydrator\Extension\ErrorsExtension'
    mrtn_json_api.document_hydrator.extension.included.class:     'Mikemirten\Component\JsonApi\Hydrator\Extension\IncludedExtension'
    mrtn_json_api.document_hydrator.extension.jsonapi.class:      'Mikemirten\Component\JsonApi\Hydrator\Extension\JsonApiExtension'

    mrtn_json_api.document.parameter_converter.class: 'Mikemirten\Bundle\JsonApiBundle\Request\JsonApiDocumentParameterConverter'

    mrtn_json_api.http_client.class:                'Mikemirten\Component\JsonApi\HttpClient\HttpClient'
    mrtn_json_api.http_client.adapter.guzzle.class: 'Mikemirten\Component\JsonApi\HttpClient\Adapter\GuzzleAdapter'
    mrtn_json_api.http_client.guzzle.class:         'GuzzleHttp\Client'

    mrtn_json_api.kernel_view.listener.class: 'Mikemirten\Bundle\JsonApiBundle\EventListener\JsonApiViewListener'

    mrtn_json_api.object_mapper.class: 'Mikemirten\Component\JsonApi\Mapper\ObjectMapper'

    mrtn_json_api.object_mapper.handler.rigid_identifier.class:      'Mikemirten\Component\JsonApi\Mapper\Handler\IdentifierHandler\RigidIdentifierHandler'
    mrtn_json_api.object_mapper.handler.class_based_type.class:      'Mikemirten\Component\JsonApi\Mapper\Handler\TypeHandler\ClassBasedTypeHandler'
    mrtn_json_api.object_mapper.handler.jms_array_transformer.class: 'Mikemirten\Component\JsonApi\Mapper\Handler\JmsArrayTransformerHandler'
    mrtn_json_api.object_mapper.handler.relationship.class:          'Mikemirten\Component\JsonApi\Mapper\Handler\RelationshipHandler'

    mrtn_json_api.view_listener.object_handler.object_mapper.class: 'Mikemirten\Bundle\JsonApiBundle\ObjectHandler\ObjectMapperHandler'

    mrtn_json_api.annotation_reader.class: 'Doctrine\Common\Annotations\AnnotationReader'

    mrtn_json_api.object_mapper.definition_provider.annotation.class: 'Mikemirten\Component\JsonApi\Mapper\Definition\AnnotationDefinitionProvider'

services:
    mrtn_json_api.document_hydrator:
        class: '%mrtn_json_api.document_hydrator.class%'

    mrtn_json_api.document_hydrator.extension.links:
        class: '%mrtn_json_api.document_hydrator.extension.links.class%'
        public: false
        tags:
            - { name: 'mrtn_json_api.document_hydrator.extension' }

    mrtn_json_api.document_hydrator.extension.metadata:
        class: '%mrtn_json_api.document_hydrator.extension.metadata.class%'
        public: false
        tags:
            - { name: 'mrtn_json_api.document_hydrator.extension' }

    mrtn_json_api.document_hydrator.extension.relationship:
        class: '%mrtn_json_api.document_hydrator.extension.relationship.class%'
        public: false
        tags:
            - { name: 'mrtn_json_api.document_hydrator.extension' }

    mrtn_json_api.document_hydrator.extension.errors:
        class: '%mrtn_json_api.document_hydrator.extension.errors.class%'
        public: false
        tags:
            - { name: 'mrtn_json_api.document_hydrator.extension' }

    mrtn_json_api.document_hydrator.extension.included:
        class: '%mrtn_json_api.document_hydrator.extension.included.class%'
        public: false
        tags:
            - { name: 'mrtn_json_api.document_hydrator.extension' }

    mrtn_json_api.document_hydrator.extension.jsonapi:
        class: '%mrtn_json_api.document_hydrator.extension.jsonapi.class%'
        public: false
        tags:
            - { name: 'mrtn_json_api.document_hydrator.extension' }

    mrtn_json_api.document.parameter_converter:
        class: '%mrtn_json_api.document.parameter_converter.class%'
        public: false
        arguments:
            - '@mrtn_json_api.document_hydrator'
        tags:
            - { name: 'request.param_converter' }

    mrtn_json_api.http_client:
        class: '%mrtn_json_api.http_client.class%'
        arguments:
            - '@mrtn_json_api.http_client.adapter.guzzle'
            - '@mrtn_json_api.document_hydrator'

    mrtn_json_api.http_client.adapter.guzzle:
        class: '%mrtn_json_api.http_client.adapter.guzzle.class%'
        public: false
        arguments:
            - '@mrtn_json_api.http_client.guzzle'

    mrtn_json_api.http_client.guzzle:
        class: '%mrtn_json_api.http_client.guzzle.class%'
        public: false

    mrtn_json_api.kernel_view.listener:
        class: '%mrtn_json_api.kernel_view.listener.class%'
        tags:
            - { name: 'kernel.event_listener', event: 'kernel.view', method: 'onKernelView' }

    mrtn_json_api.object_mapper:
        class: '%mrtn_json_api.object_mapper.class%'
        arguments:
            - '@mrtn_json_api.object_mapper.definition_provider.annotation'
            - '@mrtn_json_api.object_mapper.handler.rigid_identifier'
            - '@mrtn_json_api.object_mapper.handler.class_based_type'

    mrtn_json_api.object_mapper.handler.rigid_identifier:
        class: '%mrtn_json_api.object_mapper.handler.rigid_identifier.class%'
        public: false
        arguments: ['getId']

    mrtn_json_api.object_mapper.handler.class_based_type:
        class: '%mrtn_json_api.object_mapper.handler.class_based_type.class%'
        public: false
        arguments: [true, '.']

    mrtn_json_api.object_mapper.handler.jms_array_transformer:
        class: '%mrtn_json_api.object_mapper.handler.jms_array_transformer.class%'
        public: false
        arguments:
            - '@jms_serializer'
        tags:
            - { name: 'mrtn_json_api.object_mapper.handler' }

    mrtn_json_api.object_mapper.handler.relationship:
        class: '%mrtn_json_api.object_mapper.handler.relationship.class%'
        public: false
        tags:
            - { name: 'mrtn_json_api.object_mapper.handler' }

    mrtn_json_api.view_listener.object_handler.mapper:
        class: '%mrtn_json_api.view_listener.object_handler.object_mapper.class%'
        public: false
        arguments:
            - '@mrtn_json_api.object_mapper'
        tags:
            - { name: 'mrtn_json_api.view_listener.object_handler' }

    mrtn_json_api.annotation_reader:
        class: '%mrtn_json_api.annotation_reader.class%'
        public: false

    mrtn_json_api.object_mapper.definition_provider.annotation:
        class: '%mrtn_json_api.object_mapper.definition_provider.annotation.class%'
        public: false
        arguments:
            - '@mrtn_json_api.annotation_reader'