imports:
    - { resource: 'hydrator.yml' }
    - { resource: 'mapper.yml' }

parameters:
    mrtn_json_api.document.parameter_converter.class: 'Mikemirten\Bundle\JsonApiBundle\Request\JsonApiDocumentParameterConverter'

    mrtn_json_api.http_client.class:                'Mikemirten\Component\JsonApi\HttpClient\HttpClient'
    mrtn_json_api.http_client.adapter.guzzle.class: 'Mikemirten\Component\JsonApi\HttpClient\Adapter\GuzzleAdapter'
    mrtn_json_api.http_client.guzzle.class:         'GuzzleHttp\Client'

    mrtn_json_api.kernel_view.listener.class: 'Mikemirten\Bundle\JsonApiBundle\EventListener\JsonApiViewListener'

    mrtn_json_api.view_listener.object_handler.object_mapper.class: 'Mikemirten\Bundle\JsonApiBundle\ObjectHandler\ObjectMapperHandler'

    mrtn_json_api.annotation_reader.class: 'Doctrine\Common\Annotations\AnnotationReader'

    mrtn_json_api.object_mapper.definition_provider.annotation.class: 'Mikemirten\Component\JsonApi\Mapper\Definition\AnnotationDefinitionProvider'

services:
    mrtn_json_api.document.parameter_converter:
        class: '%mrtn_json_api.document.parameter_converter.class%'
        public: false
        arguments:
            - '@mrtn_json_api.document_hydrator'
        tags:
            - { name: 'request.param_converter' }

    mrtn_json_api.http_client:
        class: '%mrtn_json_api.http_client.class%'
        arguments:
            - '@mrtn_json_api.http_client.adapter.guzzle'
            - '@mrtn_json_api.document_hydrator'

    mrtn_json_api.http_client.adapter.guzzle:
        class: '%mrtn_json_api.http_client.adapter.guzzle.class%'
        public: false
        arguments:
            - '@mrtn_json_api.http_client.guzzle'

    mrtn_json_api.http_client.guzzle:
        class: '%mrtn_json_api.http_client.guzzle.class%'
        public: false

    mrtn_json_api.kernel_view.listener:
        class: '%mrtn_json_api.kernel_view.listener.class%'
        tags:
            - { name: 'kernel.event_listener', event: 'kernel.view', method: 'onKernelView' }

    mrtn_json_api.view_listener.object_handler.mapper:
        class: '%mrtn_json_api.view_listener.object_handler.object_mapper.class%'
        public: false
        arguments:
            - '@mrtn_json_api.object_mapper'
        tags:
            - { name: 'mrtn_json_api.view_listener.object_handler' }

    mrtn_json_api.annotation_reader:
        class: '%mrtn_json_api.annotation_reader.class%'
        public: false

    mrtn_json_api.object_mapper.definition_provider.annotation:
        class: '%mrtn_json_api.object_mapper.definition_provider.annotation.class%'
        public: false
        arguments:
            - '@mrtn_json_api.annotation_reader'